<?php

/**
 * This file is part of Galette (https://galette.eu).
 * SPDX-FileCopyrightText: Copyright © 2003-2026 The Galette Team
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

declare(strict_types=1);

namespace Galette\IO;

use DateTime;
use Galette\Core\Db;
use Galette\Core\Preferences;
use Galette\Entity\Adherent;
use Galette\Entity\PdfModel;
use Safe\DateTimeImmutable;

/**
 * Attendance sheet
 *
 * @author Johan Cwiklinski <johan@x-tnd.be>
 */

class PdfAttendanceSheet extends Pdf
{
    public const int SHEET_FONT = self::FONT_SIZE - 2;
    public const int ATT_SHEET_MODEL = 100;

    public ?string $doc_title = null;
    public ?string $sheet_title = null;
    public ?string $sheet_sub_title = null;
    public ?DateTime $sheet_date = null;
    private bool $wimages = false;

    /**
     * Page header
     */
    public function Header(): void // phpcs:ignore PSR1.Methods.CamelCapsMethodName
    {
        if ($this->PageNo() > 1) {
            $this->setTopMargin(15);
            $this->setY(10);
            $this->SetFont(Pdf::FONT, '', self::SHEET_FONT);
            $head_title = $this->doc_title;
            if ($this->sheet_title !== null) {
                $head_title .= ' - ' . $this->sheet_title;
            }
            // No "sheet_sub_title" to prevent long lines
            if ($this->sheet_date !== null) {
                $head_title .= ' - ' . $this->sheet_date->format(__("Y-m-d"));
            }
            $this->Cell(
                w: 0,
                h: 10,
                txt: $head_title,
                border: 0,
                ln: 0,
                align: 'C',
                fill: false,
                link: '',
                stretch: 0,
                ignore_min_height: false,
                calign: 'M',
                valign: 'M'
            );
        }
    }

    /**
     * Main constructor, set creator and author
     *
     * @param Db                  $zdb   Database instance
     * @param Preferences         $prefs Preferences
     * @param array<string,mixed> $data  Data to set
     */
    public function __construct(Db $zdb, Preferences $prefs, array $data = [])
    {
        $this->filename = __('attendance_sheet') . '.pdf';
        $class = PdfModel::getTypeClass(self::ATT_SHEET_MODEL);
        $model = new $class($zdb, $prefs);

        // Set document and model information
        $this->doc_title = $data['doc_title'];
        $this->SetTitle($data['doc_title']);

        if (isset($data['title']) && trim((string)$data['title']) != '') {
            $this->sheet_title = $data['title'];
            $model->title = $this->sheet_title;
        }
        if (isset($data['subtitle']) && trim((string)$data['subtitle']) != '') {
            $this->sheet_sub_title = $data['subtitle'];
            $model->subtitle = $this->sheet_sub_title;
        }
        if (isset($data['sheet_date']) && trim((string)$data['sheet_date']) != '') {
            $dformat = __("Y-m-d");
            $date = DateTime::createFromFormat(
                $dformat,
                $data['sheet_date']
            );
            $this->sheet_date = $date;
        }

        parent::__construct($prefs, $model);
        // Enable Auto Page breaks
        $this->SetAutoPageBreak(true, $this->footer_height + $this->getMargins()['bottom']);
    }

    /**
     * Initialize PDF
     */
    public function init(): void
    {
        // Set document information
        $this->SetSubject(_T("Generated by Galette"));
        $this->SetKeywords(_T("Attendance sheet"));

        $this->setHeaderMargin(10);

        // Set colors
        $this->SetDrawColor(160, 160, 160);
        $this->SetTextColor(0);
        $this->SetFont(Pdf::FONT, '', Pdf::FONT_SIZE - 2);

        //enable pagination
        $this->showPagination();

        parent::init();
    }

    /**
     * Draw members cards
     *
     * @param array<Adherent> $members Members
     */
    public function drawSheet(array $members): void
    {
        $this->PageHeader($this->doc_title);

        if ($this->sheet_date) {
            $format = __("MMMM, EEEE d y");
            $formatter = new \IntlDateFormatter(
                locale: $this->i18n->getLongID(),
                dateType: \IntlDateFormatter::FULL,
                timeType: \IntlDateFormatter::NONE,
                timezone: \date_default_timezone_get(),
                calendar: \IntlDateFormatter::GREGORIAN,
                pattern: $format
            );
            $datetime = new DateTimeImmutable($this->sheet_date->format('Y-m-d'));
            $date = DateTime::createFromImmutable($datetime);
            $date_fmt = mb_convert_case($formatter->format($date), MB_CASE_TITLE);
            $this->Cell(w: 190, h: 7, txt: $date_fmt, border: 0, ln: 1, align: 'C');
        }

        // Header
        $this->SetFont('', 'B');
        $this->SetFillColor(255, 255, 255);
        $this->Cell(w: 110, h: 7, txt: _T("Name"), border: 1, ln: 0, align: 'C', fill: true);
        $this->Cell(w: 80, h: 7, txt: _T("Signature"), border: 1, ln: 1, align: 'C', fill: true);

        // Data
        $this->SetFont('');
        $mcount = 0;
        foreach ($members as $m) {
            $mcount++;
            $this->Cell(
                w: 10,
                h: 16,
                txt: (string)$mcount,
                border: ($this->i18n->isRTL() ? 'R' : 'L') . 'TB',
                ln: 0,
                align: 'R'
            );

            if ($m->hasPicture() && $this->wimages) {
                $p = $m->picture->getPath();

                // Set logo size to max width 30 mm or max height 25 mm
                $ratio = $m->picture->getWidth() / $m->picture->getHeight();
                if ($ratio < 1) {
                    $hlogo = $m->picture->getHeight() > 14 ? 14 : $m->picture->getHeight();
                    $wlogo = round($hlogo * $ratio);
                } else {
                    $wlogo = $m->picture->getWidth() > 14 ? 14 : $m->picture->getWidth();
                    $hlogo = round($wlogo / $ratio);
                }

                $y = $this->getY() + 1;
                $x = $this->getX() + 1;
                $ximg = $x;
                if ($this->i18n->isRTL()) {
                    $ximg = $this->getPageWidth() - $x - $wlogo;
                }
                $this->Cell(w: $wlogo + 2, h: 16, txt: '', border: ($this->i18n->isRTL() ? 'R' : 'L') . 'TB', ln: 0);
                $this->Image(file: $p, x: $ximg, y: $y, w: $wlogo, h: $hlogo);
            } else {
                $x = $this->getX() + 1;
                $this->Cell(w: 1, h: 16, txt: '', border: ($this->i18n->isRTL() ? 'R' : 'L') . 'TB', ln: 0);
            }

            $xs = $this->getX() - $x + 1;
            $this->Cell(
                w: 100 - $xs,
                h: 16,
                txt: $m->sname,
                border: ($this->i18n->isRTL() ? 'L' : 'R') . 'TB',
                ln: 0,
                align: $this->i18n->isRTL() ? 'R' : 'L'
            );
            $this->Cell(w: 80, h: 16, txt: '', border: 1, ln: 1, align: $this->i18n->isRTL() ? 'R' : 'L');
        }
        $this->Cell(w: 190, h: 0, txt: '', border: 'T');
    }

    /**
     * Add images to file
     */
    public function withImages(): self
    {
        $this->wimages = true;
        return $this;
    }
}
