<?php

/**
 * This file is part of Galette (https://galette.eu).
 * SPDX-FileCopyrightText: Copyright © 2003-2026 The Galette Team
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

declare(strict_types=1);

namespace Galette\IO;

use Galette\Core\Preferences;
use Analog\Analog;
use Galette\Core\Login;
use Galette\Entity\Group;

/**
 * Groups list PDF
 *
 * @author Johan Cwiklinski <johan@x-tnd.be>
 */

class PdfGroups extends Pdf
{
    public const int SHEET_FONT = self::FONT_SIZE - 2;

    private string $doc_title;

    /**
     * Main constructor, set creator and author
     *
     * @param Preferences $prefs Preferences
     */
    public function __construct(Preferences $prefs, private readonly Login $login)
    {
        $this->filename = __('groups_list') . '.pdf';
        parent::__construct($prefs);
        // Enable Auto Page breaks
        $this->SetAutoPageBreak(true, $this->footer_height + $this->getMargins()['bottom']);
    }

    /**
     * Draws PDF page Header
     */
    public function Header(): void // phpcs:ignore PSR1.Methods.CamelCapsMethodName
    {
        $this->Cell(
            w: 0,
            h: 10,
            txt: _T("Members by groups"),
            border: 0,
            ln: 0,
            align: 'C',
            fill: false,
            link: '',
            stretch: 0,
            ignore_min_height: false,
            calign: 'M',
            valign: 'M'
        );
    }

    /**
     * Initialize PDF
     */
    public function init(): void
    {
        // Set document information
        $this->doc_title = _T("Members by groups");
        $this->SetTitle($this->doc_title);
        $this->SetSubject(_T("Generated by Galette"));

        // Set colors
        $this->SetTextColor(0, 0, 0);

        // Set margins
        $this->setMargins(10, 25);
        $this->setHeaderMargin(10);

        // Set font
        $this->SetFont(self::FONT, '', self::SHEET_FONT);

        //enable pagination
        $this->showPagination();

        parent::init();
    }

    /**
     * Draw file
     *
     * @param array<Group> $groups Groups list
     */
    public function draw(array $groups): void
    {
        $this->PageHeader($this->doc_title);

        $first = true;
        foreach ($groups as $group) {
            $id = $group->getId();
            if (!$this->login->isGroupManager($id)) {
                Analog::log(
                    'Trying to export group ' . $id . ' as PDF without appropriate permissions',
                    Analog::INFO
                );
                continue;
            }
            // Header
            if ($first === false) {
                $this->ln(5);
            }
            $this->SetFont('', 'B', self::SHEET_FONT + 1);
            $this->Cell(w: 190, h: 4, txt: $group->getName(), border: 0, ln: 1, align: 'C');
            $this->SetFont('', '', self::SHEET_FONT);

            $managers_list = $group->getManagers();
            $managers = [];
            foreach ($managers_list as $m) {
                $managers[] = $m->sfullname;
            }
            if (count($managers) > 0) {
                $this->Cell(
                    w: 190,
                    h: 4,
                    txt: _T("Managers:") . ' ' . implode(', ', $managers),
                    border: 0,
                    ln: 1,
                    align: $this->i18n->isRTL() ? 'L' : 'R'
                );
            }
            $this->ln(3);

            $this->SetFont('', 'B');
            $this->SetFillColor(255, 255, 255);
            $this->Cell(w: 80, h: 7, txt: _T("Name"), border: 1, ln: 0, align: 'C', fill: true);
            $this->Cell(w: 50, h: 7, txt: _T("Email"), border: 1, ln: 0, align: 'C', fill: true);
            $this->Cell(w: 30, h: 7, txt: _T("Phone"), border: 1, ln: 0, align: 'C', fill: true);
            $this->Cell(w: 30, h: 7, txt: _T("GSM"), border: 1, ln: 1, align: 'C', fill: true);

            $this->SetFont('', '');

            $members = $group->getMembers();

            foreach ($members as $m) {
                $align = ($this->i18n->isRTL() ? 'R' : 'L');
                $this->Cell(w: 80, h: 7, txt: $m->sname, border: 1, ln: 0, align: $align);
                $this->Cell(w: 50, h: 7, txt: $m->email, border: 1, ln: 0, align: $align);
                $this->Cell(w: 30, h: 7, txt: $m->phone, border: 1, ln: 0, align: $align);
                $this->Cell(w: 30, h: 7, txt: $m->gsm, border: 1, ln: 1, align: $align);
            }
            $this->Cell(w: 190, h: 0, txt: '', border: 'T');
            $first = false;
        }
    }
}
