<?php

/**
 * This file is part of Galette (https://galette.eu).
 * SPDX-FileCopyrightText: Copyright © 2003-2026 The Galette Team
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

declare(strict_types=1);

namespace Galette\IO;

use Galette\Core\Preferences;
use Galette\Core\PrintLogo;
use Galette\Entity\Adherent;
use Galette\Entity\Status;
use Galette\Repository\Members;

/**
 * Member card PDF
 *
 * @author Johan Cwiklinski <johan@x-tnd.be>
 * @author Fabrice Santoni <fabrice@santoni.ch>
 *
 * @since 1.3.0 New adaptative cards are the default
 */

class PdfMembersCards extends Pdf
{
    public const int PAGE_WIDTH = 210;
    public const int PAGE_HEIGHT = 297;
    public const int WIDTH = 75;
    public const int HEIGHT = 40;
    public const int COLS = 2;
    public const int ROWS = 6;

    /** @var array<string,float|int> */
    protected array $tcol;
    /** @var array<string,float|int> */
    protected array $scol;
    /** @var array<string,float|int> */
    protected array $bcol;
    /** @var array<string,float|int> */
    protected array $hcol;
    protected int $xorigin;
    protected int $yorigin;
    protected int $wi;
    protected int $he;
    protected int $nbcol;
    protected int $nbrow;
    protected int $hspacing;
    protected int $vspacing;
    protected int $max_text_size;
    protected int $year_font_size;
    protected string $an_cot;
    protected string $abrev;
    protected float $wlogo;
    protected float $hlogo;
    protected string $logofile;

    //Adaptative properties
    protected float $ratio;
    protected float $wphoto;
    protected float $hphoto;
    protected string $adh_nbr;
    protected float $cell_he;
    protected int $ban_max_he;
    protected float $email_y;
    protected int $max_text_size_full;
    protected int $max_text_size_top;
    protected int $max_text_size_center;

    /**
     * Main constructor, set creator and author
     *
     * @param Preferences $prefs Preferences
     */
    public function __construct(Preferences $prefs)
    {
        $this->setRTL(false);
        $this->filename = __('cards') . '.pdf';
        parent::__construct($prefs);
    }

    /**
     * Initialize PDF
     */
    public function init(): void
    {
        // Set document information
        $this->SetTitle(_T("Member's Cards"));
        $this->SetSubject(_T("Generated by Galette"));
        $this->SetKeywords(_T("Cards"));

        // No headers and footers
        $this->setNoHeader();
        $this->setNoFooter();

        // Show full page
        $this->SetDisplayMode('fullpage');

        // Disable Auto Page breaks
        $this->SetAutoPageBreak(false, 0);

        // Set colors
        $this->SetDrawColor(160, 160, 160);
        $this->SetTextColor(0);
        $this->tcol = $this->colorHex2Dec($this->preferences->pref_card_tcol);
        $this->scol = $this->colorHex2Dec($this->preferences->pref_card_scol);
        $this->bcol = $this->colorHex2Dec($this->preferences->pref_card_bcol);
        $this->hcol = $this->colorHex2Dec($this->preferences->pref_card_hcol);

        // Set margins
        $this->SetMargins(
            $this->preferences->pref_card_marges_h,
            $this->preferences->pref_card_marges_v
        );

        // Set font
        $this->SetFont(self::FONT);

        // Set origin
        // Top left corner
        $this->xorigin = $this->preferences->pref_card_marges_h;
        $this->yorigin = $this->preferences->pref_card_marges_v;

        // Card width
        $this->wi = self::getWidth();
        // Card height
        $this->he = self::getHeight();
        // Number of colons
        $this->nbcol = self::getCols();
        // Number of rows
        $this->nbrow = self::getRows();
        // Spacing between cards
        $this->hspacing = $this->preferences->pref_card_hspace;
        $this->vspacing = $this->preferences->pref_card_vspace;

        //maximum size for visible text. May vary with fonts.
        $this->max_text_size = 80;
        $this->year_font_size = 8;

        // Get fixed data from preferences
        $this->an_cot = $this->preferences->pref_card_year;
        $this->abrev = $this->preferences->pref_card_abrev;

        $print_logo = new PrintLogo();
        $this->logofile = $print_logo->getPath();

        // Set logo size to max width 30mm (113px) or max height 17mm (64px)
        $ratio = $print_logo->getWidth() / $print_logo->getHeight();
        if ($ratio < 1.71) {
            if ($print_logo->getHeight() > 64) {
                $this->hlogo = 17;
            } else {
                // Convert original pixels size to millimeters
                $this->hlogo = $print_logo->getHeight() / 3.78;
            }
            $this->wlogo = round($this->hlogo * $ratio);
        } else {
            if ($print_logo->getWidth() > 113) {
                $this->wlogo = 30;
            } else {
                // Convert original pixels size to millimeters
                $this->wlogo = $print_logo->getWidth() / 3.78;
            }
            $this->hlogo = round($this->wlogo / $ratio);
        }

        $this->adaptativeInit();
    }

    /**
     * Initialize adaptative cards
     */
    protected function adaptativeInit(): void
    {
        // Card width
        $this->wi = self::getWidth();
        // Card height
        $this->he = self::getHeight();
        // Number of colons
        $this->nbcol = self::getCols();
        // Number of rows
        $this->nbrow = self::getRows();

        $print_logo = new PrintLogo();

        // Set logo size to max 33% width  or max 42% height
        $this->ratio = $print_logo->getWidth() / $print_logo->getHeight();

        if ($this->ratio <= 1) {
            if ($print_logo->getHeight() > 0.42 * $this->he * 3.78) {
                $this->hlogo = round(0.42 * $this->he, 0, PHP_ROUND_HALF_DOWN);
            } else {
                // Convert original pixels size to millimeters
                $this->hlogo = $print_logo->getHeight() / 3.78;
            }
            $this->wlogo = round($this->hlogo * $this->ratio);
        } else {
            if ($print_logo->getWidth() > 0.33 * $this->wi * 3.78) {
                $this->wlogo = round(0.33 * $this->wi, 0, PHP_ROUND_HALF_DOWN);
            } else {
                // Convert original pixels size to millimeters
                $this->wlogo = $print_logo->getWidth() / 3.78;
            }
            $this->hlogo = round($this->wlogo / $this->ratio);
            // check if the logo height is greater than 42%
            if ($this->hlogo > 0.42 * $this->he) {
                $this->hlogo = round(0.42 * $this->he, 0, PHP_ROUND_HALF_DOWN);
                $this->wlogo = round($this->hlogo * $this->ratio);
            }
        }
    }

    /**
     * Draw members cards
     *
     * @param array<Adherent> $members Members
     */
    public function drawCards(array $members): void
    {
        global $zdb;

        $nb_card = 0;

        $status = new Status($zdb);
        $status_list = $status->getCompleteList();

        foreach ($members as $member) {
            // Detect page breaks
            if ($nb_card % ($this->nbcol * $this->nbrow) === 0) {
                $this->AddPage();
            }
            //maximum size for visible text. May vary with fonts.
            $this->max_text_size_full = self::getWidth();
            $this->year_font_size = (int)round(self::getWidth() / 7);

            // Compute card position on page
            $col = $nb_card % $this->nbcol;
            $row = (int)($nb_card / $this->nbcol) % $this->nbrow;

            // Set origin
            $x0 = $this->xorigin + $col * (round($this->wi) + round($this->hspacing));
            $y0 = $this->yorigin + $row * (round($this->he) + round($this->vspacing));

            // Logo X position
            $xl = round($x0 + $this->wi - $this->wlogo);

            // Baneer max height
            $this->ban_max_he = 12;

            // Get data
            $email = '';
            switch ($this->preferences->pref_card_address) {
                case 0:
                    $email .= $member->email;
                    break;
                case 5:
                    $email .= $member->zipcode . ' - ' . $member->town;
                    break;
                case 6:
                    $email .= $member->nickname;
                    break;
                case 7:
                    $email .= $member->job;
                    break;
                case 8:
                    $email .= $member->number;
                    break;
            }

            // Select strip color
            $fcol = ['R' => 0, 'G' => 0, 'B' => 0];
            if ($status_list[$member->status]['extra'] <= Members::NON_STAFF_MEMBERS) {
                $fcol = $this->bcol;
            } elseif (
                $member->status == 5 /*Benefactor member*/
                || $member->status === 6 /*Founder member*/
            ) {
                $fcol = $this->hcol;
            } elseif ($member->isActive()) {
                $fcol = $this->scol;
            }

            $nom_adh_ext = '';
            if ($this->preferences->pref_bool_display_title) {
                $nom_adh_ext .= $member->stitle . ' ';
            }
            $nom_adh_ext .= $member->sname;
            $photo = $member->picture;
            $photofile = $photo->getPath();


            // Photo 100x130 (Add a mask to crop 1/1.3)
            $this->hphoto = round($this->he * 0.75);
            $this->wphoto = $this->hphoto / 1.30;
            if ($this->wphoto > $this->wi / 3) {
                $this->wphoto = $this->wi / 3;
                $this->hphoto = $this->wphoto * 1.3;
            }
            $this->Rect(
                x: $x0 + 1,
                y: $y0 + 1,
                w: $this->wphoto,
                h: $this->hphoto,
                style: 'F',
                border_style: ['width' => 0.0, 'cap' => 'butt', 'join' => 'miter', 'dash' => 4, 'color' => [255, 255, 255]],
                fill_color: [255, 255, 255]
            );
            $this->Image(
                file: $photofile,
                x: $x0 + 1,
                y: $y0 + 1,
                w: $this->wphoto,
                h: $this->hphoto,
                type: '',
                link: '',
                align: '',
                resize: false,
                dpi: 300,
                palign: '',
                ismask: false,
                imgmask: false,
                border: 0,
                fitbox: 'T',
                hidden: false,
                fitonpage: false
            );

            // Logo
            $this->Image(file: $this->logofile, x: $xl - 1, y: $y0 + 1, w: round($this->wlogo));

            // Define max space for text
            $this->max_text_size_top = $this->max_text_size_full - intval($this->wlogo + $this->wphoto);
            $this->max_text_size_center = $this->max_text_size_full - intval($this->wphoto);

            // Color=#8C8C8C: Shadow of the year
            $this->SetTextColor(140);

            //Write shadow of the year, center of the card
            $an_cot = $this->an_cot;
            if ($an_cot === 'DEADLINE') {
                //get current member deadline
                $an_cot = $member->due_date ?? '';
            }
            $this->fixSize(
                text: $an_cot,
                maxsize: intval(round($this->max_text_size_top * 0.80, PHP_ROUND_HALF_DOWN)),
                fontsize: 14,
                fontstyle: 'B'
            );
            $this->year_font_size = intval(round($this->FontSizePt, PHP_ROUND_HALF_DOWN));
            $xan_cot = $x0 + $this->wphoto + $this->max_text_size_top / 2 - $this->GetStringWidth(
                s: $an_cot,
                fontname: self::FONT,
                fontstyle: 'B',
                fontsize: $this->year_font_size
            ) / 2;
            $this->SetXY($xan_cot, $y0 + 1);
            $this->writeHTML('<strong>' . $an_cot . '</strong>', false, false);

            // Colored Text (Big label, id, year)
            $this->SetTextColor($fcol['R'], $fcol['G'], $fcol['B']);

            //Write the year, center of the card
            $this->SetFontSize($this->year_font_size);
            $xan_cot -= 0.1;
            $this->SetXY($xan_cot, $y0 + 1 - 0.1);
            $this->writeHTML('<strong>' . $an_cot . '</strong>', false, false);

            //Write member number, center of available space
            $this->SetFontSize(8);
            $this->SetFont(self::FONT, 'B');
            $this->ratio = $this->wlogo / $this->hlogo;

            $member_id = (!empty($member->number)) ? $member->number : $member->id;
            $this->adh_nbr = _T("Member") . ' n° : ' . $member_id;
            if ($this->hlogo + 1 > 7) {
                $this->fixSize(
                    text: $this->adh_nbr,
                    maxsize: intval(round($this->max_text_size_top * 0.9, PHP_ROUND_HALF_DOWN)),
                    fontsize: 8,
                    fontstyle: 'B'
                );
                $this->SetFontSize(round($this->FontSizePt, 0, PHP_ROUND_HALF_DOWN));
                $xid = $x0 + $this->wi / 2 - $this->GetStringWidth(
                    s: $this->adh_nbr,
                    fontname: $this->FontFamily,
                    fontstyle: $this->FontStyle,
                    fontsize: $this->FontSizePt
                ) / 2 + $this->wphoto / 2 - $this->wlogo / 2;
                $this->SetXY($xid, $y0 + 8);
            } else {
                $this->fixSize(
                    text: $this->adh_nbr,
                    maxsize: intval(round($this->max_text_size_center * 0.9, PHP_ROUND_HALF_DOWN)),
                    fontsize: 10,
                    fontstyle: 'B'
                );
                $xid = $x0 + $this->wi / 2 - $this->GetStringWidth(
                    s: $this->adh_nbr,
                    fontname: $this->FontFamily,
                    fontstyle: $this->FontStyle,
                    fontsize: $this->FontSizePt
                ) / 2 + $this->wphoto / 2;
                $this->SetXY($xid, $y0 + 8);
            }
            $this->SetFontSize(round($this->FontSizePt, 0, PHP_ROUND_HALF_DOWN));
            $this->writeHTML('<strong>' . $this->adh_nbr . '  </strong>', false, false);

            // Abbrev: Adapt font size to text length
            if (13 < $this->hlogo + 1) {
                $this->fixSize(
                    text: $this->abrev,
                    maxsize: intval(round($this->max_text_size_top * 0.9, PHP_ROUND_HALF_DOWN)),
                    fontsize: 12,
                    fontstyle: 'B'
                );

                $this->SetFontSize(round($this->FontSizePt, 0, PHP_ROUND_HALF_DOWN));
                $xid = $x0 + $this->wi / 2 - $this->GetStringWidth(
                    s: $this->abrev,
                    fontname: $this->FontFamily,
                    fontstyle: $this->FontStyle,
                    fontsize: $this->FontSizePt
                ) / 2 + $this->wphoto / 2 - $this->wlogo / 2;
            } else {
                $this->fixSize(
                    text: $this->abrev,
                    maxsize: intval(round($this->max_text_size_center * 0.9, PHP_ROUND_HALF_DOWN)),
                    fontsize: 12,
                    fontstyle: 'B'
                );
                $this->SetFontSize(round($this->FontSizePt, 0, PHP_ROUND_HALF_DOWN));
                $xid = $x0 + $this->wi / 2 - $this->GetStringWidth(
                    s: $this->abrev,
                    fontname: $this->FontFamily,
                    fontstyle: $this->FontStyle,
                    fontsize: $this->FontSizePt
                ) / 2 + $this->wphoto / 2;
            }
            $this->SetXY($xid, $y0 + 13);
            $this->writeHTML('<strong>' . $this->abrev . '</strong>', true, false);

            // Name: Adapt font size to text length on one line, if font is to small on two lines
            $this->SetTextColor(0);
            $this->fixSize(
                text: $nom_adh_ext,
                maxsize: intval(round($this->max_text_size_center * 0.9, PHP_ROUND_HALF_DOWN)),
                fontsize: 8,
                fontstyle: 'B'
            );
            $this->SetFontSize(round($this->FontSizePt, 0, PHP_ROUND_HALF_DOWN));
            if ($this->hlogo + 2 >= + 20) {
                $this->SetXY($x0 + $this->wphoto + 2, $y0 + $this->hlogo + 2);
            } else {
                $this->SetXY($x0 + $this->wphoto + 2, $y0 + 20);
            }
            $this->SetFontSize(round($this->FontSizePt, 0, PHP_ROUND_HALF_DOWN));
            if ($this->FontSizePt <= 7) {
                $nom_adh_ext = '';
                if ($this->preferences->pref_bool_display_title) {
                    $nom_adh_ext .= $member->stitle . ' ';
                }
                $nom_adh_ext .= mb_strtoupper($member->name);
                $this->fixSize(
                    text: $nom_adh_ext,
                    maxsize: intval(round($this->max_text_size_center * 0.9, PHP_ROUND_HALF_DOWN)),
                    fontsize: 7,
                    fontstyle: 'B'
                );
                $this->SetFontSize(round($this->FontSizePt, 0, PHP_ROUND_HALF_DOWN));
                $this->writeHTML('<strong>' . $nom_adh_ext . '</strong>', true, false);
                $this->SetX($x0 + $this->wphoto + 2);
                $this->SetFontSize(7);

                $this->fixSize(
                    text: $member->surname,
                    maxsize: intval(round($this->max_text_size_center * 0.9, PHP_ROUND_HALF_DOWN)),
                    fontsize: 7,
                    fontstyle: 'B'
                );
                $this->SetFontSize(round($this->FontSizePt, 0, PHP_ROUND_HALF_DOWN));
                $this->writeHTML('<strong>' . $member->surname . '</strong>', true, false);
                if ($this->he < 44) {
                    $this->ban_max_he = 10;
                }
            } else {
                $this->writeHTML('<strong>' . $nom_adh_ext . '</strong>', true, false);
            }

            // Email (adapt too)
            $this->fixSize(
                text: $email,
                maxsize: intval(round($this->max_text_size_center * 0.9, PHP_ROUND_HALF_DOWN)),
                fontsize: 6,
                fontstyle: 'B'
            );
            $this->setX($x0 + $this->wphoto + 2);
            $this->writeHTML('<strong>' . $email . '</strong>', false, false);
            $this->email_y = $this->getY();

            // Lower colored strip with long text
            if ($this->wi < 73) {
                $this->max_text_size_full = (int)round($this->max_text_size_full * 0.95, PHP_ROUND_HALF_DOWN);
            }
            $this->SetFont(self::FONT, 'B');
            $this->fixSize(
                text: $this->preferences->pref_card_strip,
                maxsize: $this->max_text_size_full,
                fontsize: 12,
                fontstyle: 'B'
            );


            $this->SetFontSize(round($this->FontSizePt, 0, PHP_ROUND_HALF_DOWN));

            $this->SetFillColor($fcol['R'], $fcol['G'], $fcol['B']);
            $this->SetTextColor(
                $this->tcol['R'],
                $this->tcol['G'],
                $this->tcol['B']
            );
            //Set strip 20% height
            $this->cell_he = round($this->he * 0.20);
            if ($this->cell_he >= $this->ban_max_he) {
                $this->cell_he = $this->ban_max_he;
            }
            //Verify if strip is not over the last writen line
            if ($y0 + $this->he - $this->cell_he - 2.5 <= $this->email_y) {
                $this->cell_he = $y0 + $this->he - $this->email_y - 3;
            }
            //In case of a small strip adapt font size
            if ($this->cell_he < $this->FontSize) {
                $this->SetFontsize(round($this->cell_he * 2.83, 0, PHP_ROUND_HALF_DOWN));
            }

            $this->SetXY($x0, $y0 + $this->he - $this->cell_he);
            $this->Cell(
                w: $this->wi,
                h: $this->cell_he,
                txt: $this->preferences->pref_card_strip,
                border: 0,
                ln: 0,
                align: 'C',
                fill: true
            );

            // Draw a gray frame around the card
            $this->Rect(x: $x0, y: $y0, w: $this->wi, h: $this->he);
            $nb_card++;
        }
    }

    /**
     * Get card width
     */
    public static function getWidth(): int
    {
        global $preferences;
        return $preferences->pref_card_hsize;
    }

    /**
     * Get card height
     */
    public static function getHeight(): int
    {
        global $preferences;
        return $preferences->pref_card_vsize;
    }

    /**
     * Get number of columns
     */
    public static function getCols(): int
    {
        global $preferences;

        $margins = $preferences->pref_card_marges_h * 2;

        $nbcols = (int)round(
            ((self::PAGE_WIDTH - $margins) / $preferences->pref_card_hsize),
            0,
            PHP_ROUND_HALF_DOWN
        );
        if ((($nbcols - 1) * $preferences->pref_card_hspace + $margins + $preferences->pref_card_hsize * $nbcols) > self::PAGE_WIDTH) {
            --$nbcols;
        }

        return $nbcols;
    }

    /**
     * Get number of rows
     */
    public static function getRows(): int
    {
        global $preferences;

        $margins = $preferences->pref_card_marges_v * 2;

        $nbrows = (int)round(
            ((self::PAGE_HEIGHT - $margins) / $preferences->pref_card_vsize),
            0,
            PHP_ROUND_HALF_DOWN
        );
        if ((($nbrows - 1) * $preferences->pref_card_vspace + $margins + $preferences->pref_card_vsize * $nbrows) > self::PAGE_HEIGHT) {
            --$nbrows;
        }
        // Put two times in case of sum of the pref_card_vspace is greater than a pref_card_vsize
        if ((($nbrows - 1) * $preferences->pref_card_vspace + $margins + $preferences->pref_card_vsize * $nbrows) > self::PAGE_HEIGHT) {
            --$nbrows;
        }

        return $nbrows;
    }
}
