--
-- This file is part of Galette (https://galette.eu).
-- SPDX-FileCopyrightText: Copyright © 2003-2026 The Galette Team
-- SPDX-License-Identifier: GPL-3.0-or-later
--

ALTER TABLE galette_field_types ADD COLUMN field_specifications JSON DEFAULT NULL;

ALTER TABLE galette_types_cotisation ADD COLUMN description text;
UPDATE galette_types_cotisation SET description = '' WHERE description IS NULL;
ALTER TABLE galette_types_cotisation ALTER COLUMN description SET NOT NULL;

CREATE TABLE galette_plugins (
  plugin_id character varying(100) NOT NULL,
  version decimal DEFAULT NULL,
  PRIMARY KEY (plugin_id)
);

-- preference values no longer fit in 255 characters (footer HTML, feature flags list)
ALTER TABLE galette_preferences ALTER COLUMN val_pref TYPE text;

CREATE TABLE galette_mailing_queue (
  mailing_queue_id integer GENERATED BY DEFAULT AS IDENTITY,
  kind smallint NOT NULL DEFAULT 0,
  mailing_id integer DEFAULT NULL REFERENCES galette_mailing_history (mailing_id) ON DELETE CASCADE ON UPDATE CASCADE,
  reminder_type integer DEFAULT NULL,
  recipient_id integer DEFAULT NULL,
  recipient_email character varying(255) NOT NULL,
  recipient_name character varying(255) NOT NULL,
  status smallint NOT NULL DEFAULT 0,
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  scheduled_at timestamp DEFAULT NULL,
  sent_at timestamp DEFAULT NULL,
  PRIMARY KEY (mailing_queue_id)
);
CREATE INDEX galette_mailing_queue_status_idx ON galette_mailing_queue (status, scheduled_at);
CREATE INDEX galette_mailing_queue_sent_at_idx ON galette_mailing_queue (sent_at);

-- qmail method has been removed, fall back to sendmail (closest local MTA method)
UPDATE galette_preferences SET val_pref = '5' WHERE nom_pref = 'pref_mail_method' AND val_pref = '3';
