--
-- This file is part of Galette (https://galette.eu).
-- SPDX-FileCopyrightText: Copyright © 2003-2026 The Galette Team
-- SPDX-License-Identifier: GPL-3.0-or-later
--

-- tables for roles based access control
CREATE TABLE galette_roles (
  id_role integer GENERATED BY DEFAULT AS IDENTITY,
  role_key character varying(50) DEFAULT NULL,
  name character varying(100) NOT NULL,
  id_parent integer DEFAULT NULL REFERENCES galette_roles (id_role) ON DELETE SET NULL ON UPDATE CASCADE,
  PRIMARY KEY (id_role),
  UNIQUE (role_key),
  UNIQUE (name)
);

CREATE TABLE galette_roles_permissions (
  id_role integer NOT NULL REFERENCES galette_roles (id_role) ON DELETE CASCADE ON UPDATE CASCADE,
  permission character varying(100) NOT NULL,
  PRIMARY KEY (id_role, permission)
);

CREATE TABLE galette_members_roles (
  id_member_role integer GENERATED BY DEFAULT AS IDENTITY,
  id_adh integer NOT NULL REFERENCES galette_adherents (id_adh) ON DELETE CASCADE ON UPDATE CASCADE,
  id_role integer NOT NULL REFERENCES galette_roles (id_role) ON DELETE CASCADE ON UPDATE CASCADE,
  id_group integer DEFAULT NULL REFERENCES galette_groups (id_group) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (id_member_role),
  UNIQUE (id_adh, id_role, id_group)
);
