--
-- This file is part of Galette (https://galette.eu).
-- SPDX-FileCopyrightText: Copyright © 2003-2026 The Galette Team
-- SPDX-License-Identifier: GPL-3.0-or-later
--

ALTER TABLE galette_field_types ADD COLUMN field_specifications JSON DEFAULT NULL;

ALTER TABLE galette_types_cotisation ADD COLUMN description text;
UPDATE galette_types_cotisation SET description = '' WHERE description IS NULL;
ALTER TABLE galette_types_cotisation ALTER COLUMN description SET NOT NULL;

CREATE TABLE galette_plugins (
  plugin_id character varying(100) NOT NULL,
  version decimal DEFAULT NULL,
  PRIMARY KEY (plugin_id)
);

-- preference values no longer fit in 255 characters (footer HTML, feature flags list)
ALTER TABLE galette_preferences ALTER COLUMN val_pref TYPE text;

-- table for authentication attempts throttling
CREATE TABLE galette_auth_attempts (
  id_attempt integer GENERATED BY DEFAULT AS IDENTITY,
  scope character varying(64) NOT NULL,
  identifier character varying(255) NOT NULL,
  failures integer DEFAULT 0 NOT NULL,
  first_failure timestamp DEFAULT NULL,
  last_failure timestamp DEFAULT NULL,
  locked_until timestamp DEFAULT NULL,
  PRIMARY KEY (id_attempt),
  UNIQUE (scope, identifier)
);

CREATE TABLE galette_mailing_queue (
  mailing_queue_id integer GENERATED BY DEFAULT AS IDENTITY,
  kind smallint NOT NULL DEFAULT 0,
  mailing_id integer DEFAULT NULL REFERENCES galette_mailing_history (mailing_id) ON DELETE CASCADE ON UPDATE CASCADE,
  reminder_type integer DEFAULT NULL,
  recipient_id integer DEFAULT NULL,
  recipient_email character varying(255) NOT NULL,
  recipient_name character varying(255) NOT NULL,
  status smallint NOT NULL DEFAULT 0,
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  scheduled_at timestamp DEFAULT NULL,
  claimed_at timestamp DEFAULT NULL,
  sent_at timestamp DEFAULT NULL,
  dedup_key character varying(64) DEFAULT NULL,
  PRIMARY KEY (mailing_queue_id)
);
CREATE INDEX galette_mailing_queue_status_idx ON galette_mailing_queue (status, scheduled_at);
CREATE INDEX galette_mailing_queue_sent_at_idx ON galette_mailing_queue (sent_at);

CREATE UNIQUE INDEX galette_mailing_queue_dedup_idx ON galette_mailing_queue (dedup_key);

-- qmail method has been removed, fall back to sendmail (closest local MTA method)
UPDATE galette_preferences SET val_pref = '5' WHERE nom_pref = 'pref_mail_method' AND val_pref = '3';

-- tables for two-factor authentication
CREATE TABLE galette_twofactor (
  id_adh integer REFERENCES galette_adherents (id_adh) ON DELETE CASCADE ON UPDATE CASCADE,
  secret character varying(64) NOT NULL,
  enabled boolean DEFAULT false NOT NULL,
  date_crea timestamp NOT NULL,
  date_confirm timestamp DEFAULT NULL,
  last_timeslice bigint DEFAULT NULL,
  PRIMARY KEY (id_adh)
);

CREATE TABLE galette_twofactor_codes (
  id_code integer GENERATED BY DEFAULT AS IDENTITY,
  id_adh integer NOT NULL REFERENCES galette_adherents (id_adh) ON DELETE CASCADE ON UPDATE CASCADE,
  code character varying(255) NOT NULL,
  date_used timestamp DEFAULT NULL,
  PRIMARY KEY (id_code)
);
CREATE INDEX galette_twofactor_codes_adh ON galette_twofactor_codes (id_adh);
