name: Galette CI

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'
  pull_request:
  # Enable manual run
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  setup-phpunit-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
    steps:
      - uses: actions/checkout@v7
      - id: gen
        uses: galette/.github/actions/matrix-generator@main
        with:
          all-jobs: ${{ github.event_name != 'pull_request' && github.repository == 'galette/galette' && (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags')) }}

  setup-lint-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
    steps:
      - uses: actions/checkout@v7
      - id: gen
        uses: galette/.github/actions/matrix-generator@main
        with:
          target: lint
          all-jobs: ${{ github.event_name != 'pull_request' && github.repository == 'galette/galette' && (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags')) }}

  setup-unsupported-dbs-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
    steps:
      - uses: actions/checkout@v7
      - id: gen
        uses: galette/.github/actions/matrix-generator@main
        with:
          target: unsupported-dbs
          all-jobs: ${{ github.event_name != 'pull_request' && github.repository == 'galette/galette' && (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags')) }}

  unit-tests:
    runs-on: ubuntu-latest
    needs: setup-phpunit-matrix

    strategy:
      matrix: ${{ fromJSON(needs.setup-phpunit-matrix.outputs.matrix) }}
      fail-fast: false

    env:
      DB: ${{ matrix.db-image }}

    services:
      db:
        image: ${{ matrix.db-image }}
        env:
          POSTGRES_USER: galette_tests
          POSTGRES_PASSWORD: g@l3tte
          POSTGRES_DB: galette_tests
          MYSQL_USER: galette_tests
          MYSQL_PASSWORD: g@l3tte
          MYSQL_ROOT_PASSWORD: g@l3tte
          MYSQL_DATABASE: galette_tests
        ports:
          - 3306:3306
          - 5432:5432
        options: >-
          --health-cmd="bash -c 'if [[ -n $(command -v pg_isready) ]]; then pg_isready; else if [[ -n $(command -v mysqladmin) ]]; then mysqladmin ping; else mariadb-admin ping; fi fi'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    name: PHP ${{ matrix.php-version }} ${{ matrix.db-image }}${{ matrix.coverage == 'pcov' && ' (with coverage)' || ''}}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer, pecl
          coverage: ${{ matrix.coverage }}
          extensions: apcu
          ini-values: apc.enable_cli=1

      - name: Show database version
        run: |
          docker exec ${{ job.services.db.id }} bash -c "if [[ -n \$(command -v psql) ]]; then psql --version; else if [[ -n \$(command -v mysql) ]]; then mysql --version; else mariadb --version; fi fi"

      - name: Build Galette
        uses: galette/.github/actions/build-galette@main
        with:
          php-version: ${{ matrix.php-version }}
          enable-assets-cache: ${{ matrix.cache }}
          skip-checkout: true

      - name: Init for PostgreSQL (update)
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          bin/console galette:install -v --dbprefix=latest_galette_ --dbtype=pgsql --dbhost=localhost --dbname=galette_tests --dbuser=galette_tests --dbpass=g@l3tte --admin=admin --password=admin --no-interaction
          PGPASSWORD=g@l3tte PGCLIENTENCODING=LATIN1 psql -v ON_ERROR_STOP=1 -d galette_tests -a -f tests/pgsql_06.sql -U galette_tests -h localhost
        if: startsWith(matrix.db-image, 'postgres')

      - name: Init for MariaDB (update)
        run: |
          mysql -e 'create database IF NOT EXISTS galette_tests;' -u galette_tests --password=g@l3tte -h 127.0.0.1 -P 3306
          bin/console galette:install -v --dbprefix=latest_galette_ --dbtype=mysql --dbhost=127.0.0.1 --dbname=galette_tests --dbuser=galette_tests --dbpass=g@l3tte --admin=admin --password=admin --no-interaction
          mysql --default-character-set=latin1 -e 'use galette_tests; source tests/mysql_06.sql;' -u galette_tests --password=g@l3tte -h 127.0.0.1 -P 3306
        if: startsWith(matrix.db-image, 'mysql') || startsWith(matrix.db-image, 'mariadb')

      - name: Update database tests
        run: TESTENV=UPDATE galette/vendor/bin/phpunit --test-suffix=.php --no-coverage tests/GaletteUpdate/
        if: matrix.coverage != 'pcov'

      - name: Init for PostgreSQL
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          bin/console galette:install -v --dbtype=pgsql --dbhost=localhost --dbname=galette_tests --dbuser=galette_tests --dbpass=g@l3tte --admin=admin --password=admin --no-interaction
        if: startsWith(matrix.db-image, 'postgres')

      - name: Init for MariaDB
        run: |
          mysql -e 'create database IF NOT EXISTS galette_tests;' -u galette_tests --password=g@l3tte -h 127.0.0.1 -P 3306
          bin/console galette:install -v --dbtype=mysql --dbhost=127.0.0.1 --dbname=galette_tests --dbuser=galette_tests --dbpass=g@l3tte --admin=admin --password=admin --no-interaction
        if: startsWith(matrix.db-image, 'mysql') || startsWith(matrix.db-image, 'mariadb')

      - name: Unit tests
        run: galette/vendor/bin/phpunit --test-suffix=.php --no-coverage tests/Galette/
        if: matrix.coverage != 'pcov'

      - name: Unit tests (with coverage)
        run: galette/vendor/bin/phpunit --test-suffix=.php --coverage-filter galette/lib --coverage-clover tests/clover.xml tests/Galette/
        if: matrix.coverage == 'pcov'

      - name: Upload code coverage (scrutinizer)
        run: |
          mkdir scrutinizer
          cd scrutinizer
          composer require scrutinizer/ocular -W --ignore-platform-reqs
          php vendor/bin/ocular code-coverage:upload --format=php-clover ../tests/clover.xml
        if: matrix.coverage == 'pcov'

      - name: Upload code coverage (codecov)
        uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: 2d9dd954-bed8-4628-a267-28cd0108771b
        with:
          files: tests/clover.xml
        if: matrix.coverage == 'pcov'

      - name: Sanitize ref name for artifact upload
        if: failure()
        id: sanitize
        run: |
          db_image=$(echo -n "${{ github.event.inputs.ref }}" | sed 's/[\\\/'"'"':<>|*?]/-/g')
          echo "db_image=$db_image" >> $GITHUB_OUTPUT

      - name: Upload test data (logs, photos, etc.)
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-data-${{ matrix.php-version }}-${{ steps.sanitize.outputs.db_image }}
          path: |
            tests/tests-data/
            galette/data/logs/
            galette/data/photos/
          retention-days: 7
          if-no-files-found: ignore

  unsupported-dbs:
    runs-on: ubuntu-latest
    needs: setup-unsupported-dbs-matrix
    name: DB Fail on ${{ matrix.php-version }} ${{ matrix.db-image }}

    strategy:
      matrix: ${{ fromJSON(needs.setup-unsupported-dbs-matrix.outputs.matrix) }}
      fail-fast: false

    env:
      DB: ${{ matrix.db-image }}

    services:
      db:
        image: ${{ matrix.db-image }}
        env:
          POSTGRES_USER: galette_tests
          POSTGRES_PASSWORD: g@l3tte
          POSTGRES_DB: galette_fail_tests
          MYSQL_USER: galette_tests
          MYSQL_PASSWORD: g@l3tte
          MYSQL_ROOT_PASSWORD: g@l3tte
          MYSQL_DATABASE: galette_fail_tests
        ports:
          - 3306:3306
          - 5432:5432
        options: >-
          --health-cmd="bash -c 'if [[ -n $(command -v pg_isready) ]]; then pg_isready; else if [[ -n $(command -v mysqladmin) ]]; then mysqladmin ping; else mariadb-admin ping; fi fi'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer, pecl
          extensions: apcu
          ini-values: apc.enable_cli=1

      - name: Show database version
        run: |
          docker exec ${{ job.services.db.id }} bash -c "if [[ -n \$(command -v psql) ]]; then psql --version; else if [[ -n \$(command -v mysql) ]]; then mysql --version; else mariadb --version; fi fi"

      - name: Build Galette
        uses: galette/.github/actions/build-galette@main
        with:
          php-version: ${{ matrix.php-version }}
          enable-assets-cache: true
          skip-checkout: true

      - name: Fail database tests
        run: TESTENV=FAIL DB=${{ matrix.db-image }} galette/vendor/bin/phpunit --test-suffix=.php --no-coverage tests/GaletteDbFails/

      - name: Upload test data (logs, photos, etc.)
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-data-fail-${{ matrix.php-version }}-${{ matrix.db-image }}
          path: |
            tests/tests-data/
            galette/data/logs/
            galette/data/photos/
          retention-days: 7
          if-no-files-found: ignore

  lint:
    runs-on: ubuntu-latest
    needs: setup-lint-matrix
    name: "Lint on PHP ${{ matrix.php-version }}"

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup-lint-matrix.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer, pecl
          coverage: 'none'
          extensions: apcu
          ini-values: apc.enable_cli=1

      - name: "Show versions"
        run: |
          php --version
          composer --version

      - name: "Get Composer cache directory"
        id: composer-cache
        run: echo "dir=$(composer config -f composer.json cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache Composer dependencies"
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: "${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php-version }}-
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader --ignore-platform-reqs

      - name: CS
        run: galette/vendor/bin/phpcs

      - name: CS Fixer
        run: galette/vendor/bin/php-cs-fixer check --show-progress=dots --verbose --diff

      - name: Rector
        run: galette/vendor/bin/rector process --dry-run --ansi

      - name: Twig CS
        run: galette/vendor/bin/twigcs galette/templates/default --severity error --display blocking

      - name: Check dependencies
        run: galette/vendor/bin/composer-dependency-analyser --composer-json composer.json

      - name: PHPStan checks
        run: galette/vendor/bin/phpstan analyze --ansi --memory-limit=2G --no-interaction --no-progress

      - name: Headers checks
        run: |
          ./bin/console galette:headers:check

      - name: Check routes
        run: |
          ./bin/console galette:check-routes
